import typing


class Command(typing.Protocol):
    @property
    def name(self) -> str: ...

    @property
    def description(self) -> str: ...

    def execute(self, *args: typing.Any, **kwargs: typing.Any) -> str: ...


class Cli(typing.Protocol):
    def add_command(self, command: Command) -> typing.Self: ...

    def add_commands(self, commands: list[Command]) -> typing.Self: ...

    def run(self, argv: list[str] | None = None) -> None: ...
